const influencers = [
  'Max Lynch (@maxlynch) | Twitter',
  'Dan Abramov (@dan_abramov) | Twitter',
  'Jason Lengstorf (@jlengstorf) | Twitter',
  'Kurt Kemple (@kurtiskemple) | Twitter',
  'Kent C. Dodds (@kentcdodds)',
  'MICHAEL JACKSON (@mjackson)',
  'Ryan Florence (@ryanflorence)',
  'Scott Tolinski (@stolinski)',
  'Wes Bos (@wesbos)',
  'Marcy Sutton (@marcysutton)',
  'Sarah Drasner (@sarah_edo)',
  'Sara Soueidan (@SaraSoueidan)',
  'Rachel Andrew (@rachelandrew)',
  'Lea Verou (@LeaVerou)',
  'Andrew Clark (@acdlite)',
  'Paul Irish (@paul_irish)',
  'Sebastian Markbåge (@sebmarkbage)',
  'Brian Vaughn (@brian_d_vaughn)',
  'Sophie Alpert (@sophiebits)',
  'Pete Hunt (@floydophone)',
  'Addy Osmani (@addyosmani)',
  'Mathias Bynens (@mathias)',
  'Jake Archibald (@jaffathecake)',
  'Paul Lewis (@aerotwist)',
  'Rich Harris (@Rich_Harris)',
  'Alex Russell (@slightlylate)',
  'BrendanEich (@BrendanEich)',
  'Mike Hartington (@mhartington)',
  'zeldman (@zeldman)',
  'Kyle Mathews (@kylemathews)',
  'Max Stoiber (@mxstbr)',
  'Glen Maddern 😎 (@glenmaddern)',
  'Jason Miller 🦊⚛ (@_developit)',
  'SCRIPT GAME BRUCE WILLIS (@ken_wheeler)',
  'Brad Frost (@brad_frost)',
  'Chris Coyier (@chriscoyier)',
  'Sindre Sorhus (@sindresorhus)',
  '(1) Joel 🌧 (@jhooks)',
  'aj ⚡️ 🍜 (@ajlkn)',
  'Ryan Hoover (@rrhoover)',
  'Courtland Allen (@csallen)',
  'Marc Andreessen (@pmarca)'
]

module.exports = influencers.map(i => i.match(/@\w*/gi)[0])
